import Head from 'next/head'
import Image from 'next/legacy/image'
import Photo from './../../public/assets/Béa_2014.webp'
import styles from '@/styles/Home.module.css'
import About from '@/components/About/About'
import Naturopathie from '@/components/Naturopathie/Naturopathie'
import Bioresonance from '@/components/Bioresonance/Bioresonance'
import Contact from '@/components/Contact/Contact'
import Massage from '@/components/Massage/Massage'
import Physionutrition from '@/components/Physionutrition/Physionutrition'
import Prices from '@/components/Prices/Prices'
import Testimonials from '@/components/Testimonials/Testimonials'
import UpButton from '@/components/UpButton/UpButton'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section id="Accueil">
              <div data-aos='flip-right' data-aos-easing="linear" data-aos-duration="1000">
                  <Image src={Photo} alt="Beatrice Fabry, naturopathe" />
              </div>
              <div data-aos='flip-left' data-aos-easing="linear" data-aos-duration="1000" className={styles.presentation}>
                  <h1>Béatrice FABRY</h1>
                  <p>
                      Naturopathe
                  </p>
                  <p>
                      Thérapeute en biorésonance
                  </p>
                  <p>
                      Physionutritionniste diplômée IEPP
                  </p>
                  <p>
                      Massage Amma
                  </p>
                  <a href = '#Contact'>Contactez-moi</a>
              </div>
          </section>
          <About/>
          <Naturopathie/>
          <Bioresonance/>
          <Physionutrition/>
          <Massage/>
          <Prices/>
          <Contact/>
          <Testimonials/>
          <UpButton/>      
      </main>
    </>
  )
}
